### ISSUE TITLE
Implement User Authentication Feature

### ISSUE THREAD

**Issue by Joecode22** [Joecode22/Chat-With-ResumeV2#7]
Description:
As a software engineer, I need to implement a user authentication feature to allow users to securely log in to our application. This feature will support both standard email/password login and OAuth for Google and Facebook. It should also include a "Forgot Password?" functionality that allows users to reset their password via email.

Acceptance Criteria:

Users can create a new account using their email and password.
Users can log in using their email and password.
Users can log in using Google OAuth.
Users can log in using Facebook OAuth.
There is a "Forgot Password?" feature that allows users to reset their password through a link sent to their email.
Input validation for the email and password fields.
Unit tests cover new functionalities.
Integration tests validate the interaction with the email service and OAuth providers.
Tasks:

 Design the database schema for user authentication.
 Implement the backend logic for the email/password authentication.
 Integrate Google OAuth.
 Integrate Facebook OAuth.
 Develop the frontend UI for the login and signup pages.
 Implement the "Forgot Password?" feature.
 Write unit tests for the backend logic.
 Write integration tests.

**Comment by jeromehardaway** [comment]
@jeromehardaway

**Comment by Joecode22** [comment]
@jeromehardaway

**Comment by jeromehardaway** [comment]
Approved
